# Based on example from https://github.com/julia-actions/julia-runtest
name: Run tests

on: [push, pull_request, workflow_dispatch]

permissions:
  actions: write
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
      fail-fast: false
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
      - run: |
          # Need to use openmpi so that we can use `--oversubscribe` to allow using more MPI ranks than physical cores
          julia --project -O3 -e 'import Pkg; Pkg.add(["MPIPreferences"]); using MPIPreferences; MPIPreferences.use_jll_binary("OpenMPI_jll")'
          julia --project -O3 -e 'using MPI; MPI.install_mpiexecjl(; destdir=".")'
          for np in {1,2,4,8}; do ./mpiexecjl -np $np --oversubscribe julia --project -O3 -e 'using Pkg; Pkg.test()'; done
